image: openjdk:8-jdk

stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - .gradle/

compile:
  stage: build
  script:
    - ./gradlew --console=plain --stacktrace assemble
  artifacts:
    paths:
        - build/libs/*.jar
    expire_in: 30 days

unit test:
  stage: test
  script:
    - ./gradlew --console=plain --stacktrace test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

coverage and javadoc:
  stage: test
  script:
    - ./gradlew --console=plain --stacktrace test jacocoTestReport javadoc
    - cat build/jacoco/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - build/jacoco/html/
      - build/docs/javadoc/

pages:
  stage: deploy
  dependencies:
    - coverage and javadoc
  script:
    - mkdir public
    - mv build/jacoco/html/ public/coverage
    - mv build/docs/javadoc/ public/javadoc
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
