image: openjdk:8-jdk

stages:
  - build
  - test
  - deploy

cache:
compile:
  stage: build
  script:
    - ./gradlew assemble
  tags:
    - jdk:8

coverage:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
    - cat build/jacoco/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - build/jacoco/html/
  only:
    - master

pages:
  stage: deploy
  dependencies: 
    - coverage
  script:
    - mv build/jacoco/html/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master